[[redirects]]
  from = "/standings/*"
  to = "https://standings-decorde.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ihs/*"
  to = "https://ihsapp.netlify.app/:splat"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
